"""empty message

Revision ID: 54010e32c0d9
Revises: 99a4c3370700
Create Date: 2024-06-30 12:43:46.687050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54010e32c0d9'
down_revision = '99a4c3370700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
